"""Add Review Model

Revision ID: b9eedf58bff0
Revises: 09c7788596c4
Create Date: 2025-05-30 11:23:10.980093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9eedf58bff0'
down_revision = '09c7788596c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
